version: 2.1
jobs:
  compile:
    machine:
      image: circleci/classic:latest
    steps:
      - run: sudo apt install -qq bc zip make m4 gcc clang zlib1g-dev libstdc++6
      - checkout
      - run: wget https://raw.githubusercontent.com/najahiiii/Noob-Script/noob/circle
      - run: chmod +x circle
      - run: bash circle
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
